(function(g){var window=this;'use strict';var H4=function(a){a.ra("cardstatechange",a.Mk()&&a.So()?1:0)},I4=function(a,b){var c=g.Wa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},sfb=function(a){var b=g.qo(a);
a=g.to(a);return new g.Rn(b.x,b.y,a.width,a.height)},L4=function(a){a=g.ab(a);
delete J4[a];g.id(J4)&&K4&&K4.stop()},ufb=function(){K4||(K4=new g.Kq(function(){tfb()},20));
var a=K4;a.isActive()||a.start()},tfb=function(){var a=g.eb();
g.Wc(J4,function(b){vfb(b,a)});
g.id(J4)||ufb()},M4=function(a,b,c,d){g.dr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.J=0;this.C=null},vfb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.C);a.C=b;wfb(a,a.progress);1==a.progress?(a.j=0,L4(a),a.onFinish(),a.vr()):a.wd()&&a.lK()},wfb=function(a,b){"function"===typeof a.D&&(b=a.D(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},xfb=function(a,b){g.yb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},N4=function(a,b,c,d,e){M4.call(this,b,c,d,e);
this.element=a},yfb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
N4.call(this,a,b,c,d,e)},zfb=function(a){return Math.pow(a,3)},Afb=function(a){return 3*a*a-2*a*a*a},Bfb=function(a){g.G.call(this);
this.u=a||window;this.j=[]},O4=function(a){return a.baseUrl||null},P4=function(a,b){return g.cp(g.kn(a,b),function(c){return!!c})},Cfb=function(a,b,c){function d(ca){var ha=ca.hovercardButton;
if(!ha)return null;ha=ha.subscribeButtonRenderer;if(!ha)return null;var Da=f(ha.unsubscribedButtonText),fa=f(ha.subscribedButtonText);if(ha.subscribed){var U=f(ha.subscriberCountWithUnsubscribeText);var Ua=f(ha.subscriberCountText)}else U=f(ha.subscriberCountText),Ua=f(ha.subscriberCountWithSubscribeText);var r=null;if(ca.signinEndpoint){r=I4(ca,"signinEndpoint","webNavigationEndpointData","url");if(!r){var V,ob;r=null==(ob=g.Q(null==(V=ha.signInEndpoint)?void 0:V.commandMetadata,g.A3))?void 0:ob.url}if(!r)return null}return Da&&
(fa||r)?{subscribed:ha.subscribed,subscribeText:Da,subscribeCount:U,unsubscribeText:fa,unsubscribeCount:Ua,enabled:ha.enabled,signinUrl:r,classic:ca.useClassicSubscribeButton}:null}
function e(ca){if(ca){var ha=[],Da=ca.videoId;Da&&ha.push("v="+Da);(Da=ca.playlistId)&&ha.push("list="+Da);(ca=ca.startTimeSeconds)&&ha.push("t="+ca);return"/watch?"+ha.join("&")}}
function f(ca){if(!ca)return null;var ha=ca.simpleText;return ha?ha:ca.runs?g.kn(ca.runs,function(Da){return Da.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,y=null,A=!1,E=null,K=null,I=null,F=null,S=null,Y=null;if("VIDEO"===h)g.Q(l,g.rO)?m=g.Q(l,g.rO).url:(Y=g.Q(l,g.qO),m=e(Y)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===h)g.Q(l,g.rO)?m=g.Q(l,g.rO).url:(Y=g.Q(l,g.qO),m=e(Y)),n=!1,q=a,v=f(b.playlistLength);else if("CHANNEL"===
h){if(A=I4(l,"browseEndpoint","browseId"))y=A,m="/channel/"+y;n=!1;q="new";(A=!!b.isSubscribe)?E=d(b):K=f(b.subscribersText)}else"WEBSITE"===h?((I=I4(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(S=f(b.additionalFeesText)),(n=I4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=I4(b,"title","accessibility","accessibilityData","label");var ia=b.endpoint?b.endpoint.clickTrackingParams:null,
ta="";if(b.metadata){var na=f(b.metadata);na&&(ta=na)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ta,callToAction:f(b.callToAction),LU:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,kD:p,playlistLength:v,channelId:y,subscribeButton:E,subscribersText:K,isSubscribe:A,xu:m||null,R5:n,sessionData:ia?{itct:ia}:null,K$:q,NB:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:P4(b.impressionUrls||[],O4),G5:P4(b.hovercardShowUrls||[],O4),clickUrls:P4(l.loggingUrls||[],O4),visualElement:g.pH(b.trackingParams),productPrice:F,additionalFeesText:S,watchEndpoint:Y||null}},Dfb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:P4(a.impressionUrls||[],O4),elements:P4(a.elements||[],function(d,e){return Cfb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.pH(a.trackingParams));return c},Efb=function(a){g.WT.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.ea=!0;this.J=0;a=a.W();this.V=g.CM(a)||"profilepage"===a.Fa;this.events=new g.PK(this);g.H(this,this.events);this.events.T(this.player,g.PG("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.QG("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Kb);this.events.T(window,"focus",this.r9);this.load();var b=g.bf("STYLE");(g.Ke("HEAD")[0]||document.body).appendChild(b);g.tb(this,
function(){g.pf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Ffb=function(a){return a.player.getVideoData().Dd?"current":a.V?"new":"current"},Q4=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Gfb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Dfb(f,Ffb(a))));R4(a,f)},
urlParams:{v:c},withCredentials:!0};a.V&&(c.urlParams.ptype="embedded");var d=b.yx;d&&(c.postParams={ad_tracking:d});if(b=g.Qza(b))if(b=g.be(b),b=g.$d(b))a.B=g.hA(b,c)},R4=function(a,b,c){c=void 0===c?!0:c;
a.player.Se("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&Hfb(a);c=[];d=new g.NG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().u||(a.u=new g.X({G:"div",S:"ytp-ce-shadow"}),g.XS(a.player,a.u.element,4),a.C=new g.yR(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Ifb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.XS(a.player,f.element,4);var h=new g.NG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Jfb(a,f,e)}else g.tG(new g.EB("buildEndscreenElement null",
e))}a.player.hf(c);a.Kb()}},Hfb=function(a){var b=g.rH(),c=g.sH();
c&&b&&a.endscreen.visualElement&&g.Nz(g.jQ)(void 0,c,b,a.endscreen.visualElement)},Ifb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Na:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.NB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:S4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:T4(a,b.xu),tabindex:"-1"},X:[{G:"div",Na:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.hr(b.title||"")},Aa:b.title},{G:"div",S:b.kD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",Aa:b.videoDuration||
void 0}]}]};c=new g.X(a);break;case "PLAYLIST":a={G:"div",Na:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.NB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-covering-image",Y:S4(b)},{G:"div",S:"ytp-ce-covering-shadow-top"},{G:"a",S:"ytp-ce-covering-overlay",Y:{href:T4(a,b.xu),tabindex:"-1"},X:[{G:"div",Na:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.hr(b.title||"")},Aa:b.title},{G:"div",S:"ytp-ce-playlist-count",X:[{G:"div",S:"ytp-ce-playlist-icon"},
{G:"div",S:"ytp-ce-playlist-count-text",Aa:b.playlistLength||void 0}]}]}]};c=new g.X(a);break;case "CHANNEL":c={G:"div",Na:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.NB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"a",Na:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:T4(a,b.xu),target:"_blank",tabindex:"-1",dir:g.hr(b.title||"")},Aa:b.title},b.subscribeButton?{G:"div",S:"ytp-ce-subscribe-container",X:[{G:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",S:"ytp-ce-channel-subscribers-text",Aa:b.subscribersText}:"",b.metadata?{G:"div",Na:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
Aa:b.metadata}:""]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)}]};c=new g.X(c);var d=g.Le(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.Sq(d,"ytp-ce-subscribe-button");if(a.player.W().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.LU(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Na:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.NB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",
S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-website-title",Y:{dir:g.hr(b.title||"")},Aa:b.title},{G:"div",S:"ytp-ce-website-metadata",Aa:b.metadata},{G:"a",Na:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:T4(a,b.xu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)},{G:"div",S:"ytp-ce-expanding-icon",Y:Kfb(b.iconUrl)}]};c=new g.X(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",S:"ytp-ce-merchandise-price-container",
X:[{G:"div",S:"ytp-ce-merchandise-price",Aa:b.productPrice}]},b.additionalFeesText&&c.X.push({G:"div",S:"ytp-ce-merchandise-additional-fees",Aa:b.additionalFeesText})),a={G:"div",Na:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.NB||"","aria-hidden":"true"},X:[{G:"div",S:"ytp-ce-element-shadow"},{G:"div",S:"ytp-ce-expanding-overlay",X:[{G:"div",S:"ytp-ce-expanding-overlay-hider"},{G:"div",S:"ytp-ce-expanding-overlay-background"},{G:"div",S:"ytp-ce-expanding-overlay-content",
X:[{G:"div",S:"ytp-ce-expanding-overlay-body",X:[{G:"div",S:"ytp-ce-expanding-overlay-body-padding",X:[{G:"div",S:"ytp-ce-merchandise-title",Y:{dir:g.hr(b.title||"")},Aa:b.title},c,{G:"div",S:"ytp-ce-merchandise-metadata",Aa:b.metadata},{G:"a",Na:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:T4(a,b.xu),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{G:"div",S:"ytp-ce-expanding-image",Y:S4(b)},{G:"div",S:"ytp-ce-merchandise-invideo-cta-container",X:[{G:"div",S:"ytp-ce-merchandise-invideo-cta",
Aa:b.callToAction||void 0}]}]},c=new g.X(a)}b.isPlaceholder&&g.Sq(c.element,"ytp-ce-placeholder");return c},S4=function(a){if(a.LU)var b=a.LU.thumbnails;
return Kfb(b?b[b.length-1].url:null)},Kfb=function(a){return a?{style:"background-image: url("+a+")"}:{}},Jfb=function(a,b,c){function d(m){m&&(b.Ta("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.Sq(b.element,"ytp-ce-force-expand"),U4(a,c.id,!0)):(g.Uq(b.element,"ytp-ce-force-expand"),g.Uq(b.element,"ytp-ce-element-hover"),U4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ta("mouseenter",function(){Lfb(a,b,c)});
b.Ta("mouseleave",function(){Mfb(a,b,c)});
a.player.W().u||b.Ta("click",function(){g.Sq(b.element,"ytp-ce-element-hover")});
b.Ta("click",function(m){Nfb(a,c,m)});
b.Ta("keypress",function(m){Nfb(a,c,m)});
b.Ta("focus",function(){Lfb(a,b,c)});
b.Ta("blur",function(){Mfb(a,b,c)});
b.Ta("touchstart",function(){Lfb(a,b,c)});
var l=g.Ne("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){g.QP?m.stopPropagation():(m=m||window.event,m.cancelBubble=!0,m.stopPropagation&&m.stopPropagation());g.Uq(b.element,"ytp-ce-element-hover");g.Uq(b.element,"ytp-ce-force-expand")});
b.Ta("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.Ne("ytp-sb-subscribe",b.element));d(g.Ne("ytp-sb-unsubscribe",b.element));b.Ta("focus",f);b.Ta("blur",h)},Nfb=function(a,b,c){if(b.xu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Rq(d,"ytp-ce-element");){g.Rq(d,"subscribe-label")&&Ofb(a,b);
if(g.Rq(d,"ytp-ce-channel-subscribe"))return;d=g.qf(d)}if(!d||g.Rq(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Mfb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.K$)Ofb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.be(T4(a,b.xu)),g.sP(g.$d(c),void 0,b.sessionData);else{var e=g.QM(a.player.W())||a.player.getVideoData().Dd,f=function(){var h=T4(a,b.xu),l=b.sessionData,m=b.watchEndpoint,n=g.Tz(h);e&&n&&(n.v||n.list)?a.player.xo(n.v,
l,n.list,!1,void 0,m||void 0):g.xAa(h,l)};
Ofb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},T4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.YM(a)+b}else return"";return b},Lfb=function(a,b,c){g.Rq(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.Sq(b.element,"ytp-ce-element-hover"):a.player.W().u?(new g.Kq(function(){g.Sq(b.element,"ytp-ce-element-hover")},200)).start():g.Sq(b.element,"ytp-ce-element-hover"),V4(a,c.G5),U4(a,c.id,!0))},Mfb=function(a,b,c){g.Uq(b.element,"ytp-ce-element-hover");
g.Uq(b.element,"ytp-ce-force-expand");U4(a,c.id,!1)},U4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Wq(a.j[e].element,"ytp-ce-element-shadow-show",c)},V4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Q4(a))c&&c();else{b=Pfb(a,b);var e=0,f=!1,h=new g.Kq(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.wD(b[a],d)}},Ofb=function(a,b,c){V4(a,b.clickUrls,c);
(a=g.sH())&&b.R5&&g.qQ(a,b.visualElement)},Pfb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Qfb(b[d],c));return a},Qfb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Rfb=function(a){return"string"===typeof a?a:""},W4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Sfb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},X4=function(a){return a.value?a.value:null},Y4=function(a){if(!a)return null;
var b=g.be(Rfb(a.value));b=g.$d(b);if(!b)return null;var c=W4(a.target,Tfb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Sfb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Ufb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Xfb=function(a){if(!a)return null;
var b=W4(a.type,Vfb),c=W4(a.trigger,Wfb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y4(a?a:null);return b?new Ufb(b,c,a):null},Yfb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Zfb=function(a,b){return g.Db(a.action,b)},$fb=function(a,b){this.context=a;
this.j=b},agb=function(a){return a.customMessage?Z4("div","iv-card-message",a.customMessage):""},$4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",S:"iv-card-image",Y:{style:a},X:c}},bgb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z4("li","",c.value));return{G:"ul",S:"iv-card-meta-info",X:b}},Z4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.hr(c);return{G:a,Y:b,Aa:c}},cgb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.VB&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.VB+");");c.dir=g.hr(a.customMessage);var d=[{G:"span",Aa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",S:"iv-card-link-icon"}));return{G:"div",Na:b,Y:c,X:d}},a5=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},dgb=function(a,b){this.merchant=a;
this.price=b},egb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},fgb=function(a,b){return b?b:egb(a)?"current":"new"},b5=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.eb=new Map;this.kb=new Map;this.context.I.addEventListener(g.PG("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.QG("annotations_module"),function(d){(d=c.kb.get(d))&&d.apply(c)})},c5=function(a,b,c,d,e,f,h){a.context.j.Ta(b,"click",function(l){a.mK(c,d,e,f||[],h||0,l)});
a.context.j.Ta(b,"touchstart",function(){a.wb=!1});
a.context.j.Ta(b,"touchmove",function(){a.wb=!0})},ggb=function(a){var b;
return(null==(b=g.Q(a,g.rO))?0:b.url)?g.Q(a,g.rO).url:(a=g.Q(a,g.qO))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},d5=function(a,b,c){return{hW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
IZ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
CJ:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},hgb=function(a,b,c){b5.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Oa=this.hc=this.B=this.isInitialized=!1;this.cards=[];this.Eb=this.V=this.Ma=this.D=this.Ya=this.j=null;this.oa=[];this.qa=this.K=this.xg=this.Fa=null;this.J=0;this.Ga=new g.Kq(function(){},c.Z.Pi?4E3:3E3);
g.H(this,this.Ga);this.rb=new g.Kq(function(){});
g.H(this,this.rb);this.Ba=new $fb(c,function(e,f,h,l,m,n){c5(d,e,f,h,l,m,n)});
this.ea=new g.X({G:"div",S:"iv-drawer",Y:{id:"iv-drawer"},X:[{G:"div",S:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{G:"span",S:"iv-drawer-header-text"},{G:"button",Na:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",S:"iv-drawer-content"}]});g.H(this,this.ea);this.C=this.ea.element;this.ob=new g.yR(this.ea,330);g.H(this,this.ob);this.Zb=g.Ne("iv-drawer-header-text",this.C);this.u=g.Ne("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.hc&&e5(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.hc=d.B)&&f5(d)});
this.Va=new g.PK(this);g.H(this,this.Va);this.I.addEventListener("videodatachange",this.vt.bind(this))},igb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){e5(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){f5(a)});
var c=b.headerText;g.sf(a.Zb,c);a.V&&a.V.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.pH(b.trackingParams);a.K=g.pH(b.closeTrackingParams);a.xg=g.pH(b.iconTrackingParams)},jgb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.W().experiments.sb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.VG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},To:null,zl:e.trackingParams?g.pH(e.trackingParams):null,xg:f&&f.trackingParams?g.pH(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
VB:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};g5(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.VG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:h5(a,c,b,f),sponsored:!1,bj:d5(f,e,f.command),To:f.trackingParams?g.pH(f.trackingParams):null,zl:e.trackingParams?g.pH(e.trackingParams):null,xg:l&&l.trackingParams?g.pH(l.trackingParams):null,imageUrl:i5(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.VG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,VB:null,title:f.title?g.VG(f.title):"",customMessage:f.callToAction?g.VG(f.callToAction):"",url:g.Q(f.command,g.rO).url?Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(f.command,g.rO).url}):null,onClickCommand:null};g5(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.VG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,bj:d5(e,f,e.endpoint),To:e.trackingParams?g.pH(e.trackingParams):null,zl:f.trackingParams?g.pH(f.trackingParams):null,xg:l&&l.trackingParams?g.pH(l.trackingParams):null,channelId:g.Q(e.endpoint,g.z3).browseId,customMessage:e.customText?g.VG(e.customText):null,wY:i5(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.VG(e.channelName):"",metaInfo:[e.subscriberCountText?g.VG(e.subscriberCountText):""],url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.Q(e.endpoint,g.z3).canonicalBaseUrl?g.Q(e.endpoint,g.z3).canonicalBaseUrl:"/channel/"+g.Q(e.endpoint,g.z3).browseId}),onClickCommand:null};g5(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.VG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,bj:d5(e,f,e.action),To:e.trackingParams?g.pH(e.trackingParams):null,zl:f.trackingParams?g.pH(f.trackingParams):null,xg:l&&l.trackingParams?g.pH(l.trackingParams):null,dF:i5(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.VG(e.customMessage):null,playlistVideoCount:g.VG(e.playlistVideoCount),title:e.playlistTitle?g.VG(e.playlistTitle):"",metaInfo:[e.channelName?g.VG(e.channelName):
"",e.videoCountText?g.VG(e.videoCountText):""],url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ggb(e.action)}),onClickCommand:null};g5(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.VG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:h5(a,c,b,e),sponsored:!1,bj:d5(e,f,e.action),To:e.trackingParams?g.pH(e.trackingParams):null,zl:f.trackingParams?g.pH(f.trackingParams):null,xg:l&&l.trackingParams?g.pH(l.trackingParams):null,dF:i5(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.VG(e.lengthString):null,customMessage:e.customMessage?g.VG(e.customMessage):null,title:e.videoTitle?g.VG(e.videoTitle):"",metaInfo:[e.channelName?g.VG(e.channelName):
"",e.viewCountText?g.VG(e.viewCountText):""],isLiveNow:!!e.badge,url:Y4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ggb(e.action)}),onClickCommand:null};g5(a,b)}}}}}a.J++},i5=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h5=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},lgb=function(a,b){if(b=kgb(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.rg.id),g.pf(b.SL),g.Hb(a.cards,b),a.cG(),j5(a)},e5=function(a,b,c){if(!a.B){a.ob.show();
a.Ya=new g.Kq(function(){g.Sq(a.context.I.getRootNode(),g.xX.IV_DRAWER_OPEN)},0);
a.Ya.start();a.Va.T(a.u,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.sH();d&&a.Fa&&a.K&&g.oQ(d,[a.Fa,a.K]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.WW||(f.WW=!0,mgb(a.context.logger,f.rg.bj.hW,b)),d&&g.oQ(d,[f.rg.To]);H4(a.I);c&&(a.D=new g.Kq(function(){a.Ma=a.V;a.Eb.focus()},330),a.D.start())}},f5=function(a){a.B&&(a.ob.hide(),g.nB(a.Va),g.Uq(a.context.I.getRootNode(),g.xX.IV_DRAWER_OPEN),a.B=!1,H4(a.I),a.D&&a.D.stop(),a.D=new g.Kq(function(){a.Ma&&(a.Ma.focus(),a.Ma=null)},330),a.D.start())},ogb=function(a){g.Tq(a.Bb(),
[g.xX.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.XS(a.I,a.C,5);ngb(a);a.V=g.Ne("ytp-cards-button",a.I.getRootNode());a.Eb=g.Ne("iv-drawer-close-button",a.C);a.isInitialized=!0},ngb=function(a){var b=g.Ne("iv-drawer-close-button",a.C);
a.context.j.Ta(b,"click",a.T3,a);a.context.j.Ta(a.u,"touchend",function(){a.Ga.start()});
a.context.j.Ta(a.u,"scroll",a.n4,a);a.context.u.subscribe("onHideControls",function(){a.Oa=!0});
a.context.u.subscribe("onShowControls",function(){a.Oa=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Oa=g.Rq(a.I.getRootNode(),"ytp-autohide")});
a.oa.push(g.ND("iv-button-shown",a.c6,a));a.oa.push(g.ND("iv-button-hidden",a.b6,a));a.oa.push(g.ND("iv-teaser-shown",a.v0,a));a.oa.push(g.ND("iv-teaser-hidden",a.d6,a));a.oa.push(g.ND("iv-teaser-clicked",a.u0,a))},pgb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.Q(b.onClickCommand,g.bcb))?void 0:c.targetId)?(a.qa=b,!0):!1},qgb=function(a,b){a.qa=b;
var c=a.I.getVideoData();if(!c)return!1;c=a.I.N("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.iya(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.Q(h[0],g.VQa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},
g5=function(a,b){if(!pgb(a,b)||qgb(a,b)){var c=rgb(a,b);
if(c){var d={rg:b,SL:c.element,WW:!1};if(!b.onClickCommand){a.isInitialized||ogb(a);lgb(a,b.id);var e=sgb(a,d);g.Qb(a.cards,e,0,d);c.Ja(a.u,e);a.cG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,j5(a),tgb(a,d),e5(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&ugb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){ugb(a,d)}),j5(a))}}},rgb=function(a,b){switch(b.type){case "simple":a=a.Ba;
var c=b.displayDomain?{G:"div",S:"iv-card-image-text",Aa:b.displayDomain}:void 0;var d=cgb(b);c={G:"div",Na:["iv-card"],X:[{G:"a",S:"iv-click-target",Y:{href:b.url?X4(b.url)||"":""},X:[$4(b.imageUrl,c),{G:"div",S:"iv-card-content",X:[Z4("h2",void 0,b.title),d]}]}]};c=new g.X(c);a5(a,g.Me("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ba;c={G:"div",Na:["iv-card","iv-card-channel"],X:[{G:"a",Na:["iv-click-target"],Y:{href:X4(b.url)||"","data-ytid":b.channelId},X:[$4(b.wY),{G:"div",
S:"iv-card-content",X:[agb(b),{G:"h2",S:"iv-card-primary-link",Aa:b.title},bgb(b)]}]}]};c=new g.X(c);a5(a,g.Me("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ba;c={G:"div",Na:["iv-card","iv-card-playlist"],X:[{G:"a",S:"iv-click-target",Y:{href:X4(b.url)||""},X:[$4(b.dF,{G:"div",S:"iv-card-image-overlay",X:[{G:"span",S:"iv-card-playlist-video-count",Aa:b.playlistVideoCount}]}),{G:"div",S:"iv-card-content",X:[agb(b),Z4("h2","iv-card-primary-link",b.title),bgb(b)]}]}]};c=new g.X(c);
a5(a,g.Me("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ba;var e=0!=b.offers.length;c=["iv-card"];d="";var f=cgb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",S:"iv-card-offer-price",Aa:f.price}),f.merchant&&e.push({G:"div",S:"iv-card-offer-merchant",Aa:f.merchant}),f={G:"div",X:e});e=b.url?X4(b.url)||"":"";c={G:"div",Na:c,Y:{tabindex:"0"},X:[{G:"a",Na:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",S:"iv-card-content",X:[b.sponsored?{G:"div",S:"iv-card-sponsored",X:["Sponsored",{G:"div",S:"iv-ad-info-container",X:[{G:"div",S:"iv-ad-info",Aa:"{{adInfo}}"},{G:"div",S:"iv-ad-info-icon-container",X:[{G:"div",S:"iv-ad-info-icon"},{G:"div",S:"iv-ad-info-callout"}]}]}]}:"",{G:"a",S:"iv-click-target",Y:{href:e},X:[Z4("h2",d,b.title),f]}]}]};c=new g.X(c);d=g.bf("span");g.sf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.qe(d,"adInfo");a5(a,g.Me("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ba;d=b.videoDuration?{G:"span",S:"iv-card-video-duration",Aa:b.videoDuration}:void 0;f=b.isLiveNow?{G:"span",Na:["yt-badge","yt-badge-live"],Aa:"LIVE NOW"}:null;e={G:"div",Na:["iv-card","iv-card-video"],X:[{G:"a",S:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:X4(c))||""},X:[$4(b.dF,d),{G:"div",S:"iv-card-content",X:[agb(b),Z4("h2","iv-card-primary-link",b.title),bgb(b),f]}]}]};c=new g.X(e);a5(a,g.Me("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},sgb=function(a,b){if(0===a.cards.length)return 0;
a=g.Eb(a.cards,function(c){return b.rg.startMs>c.rg.startMs||b.rg.startMs===c.rg.startMs&&b.rg.timestamp>=c.rg.timestamp?!0:!1});
return-1===a?0:a+1},vgb=function(a){if(a.j)return"productListing"===a.j.rg.type;
if(a.I.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.ln(a.cards,function(c){return"productListing"===c.rg.type})}return g.ln(a.cards,function(c){return"productListing"===c.rg.type})},j5=function(a){g.Wq(a.I.getRootNode(),"ytp-cards-shopping-active",vgb(a))},ugb=function(a,b){if(!g.Rq(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.sH(),d=a.j?a.j.rg.xg:a.xg;
c&&d&&g.pQ(c,[d]);a.j=b;j5(a)}(c=a.isInitialized&&"none"==a.Bb().style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.rg.teaserDurationMs&&a.I.yA(!0,{teaserText:b.rg.teaserText,durationMs:b.rg.teaserDurationMs,onClickCommand:b.rg.onClickCommand});a.rb.isActive()||((!a.B||!a.Ga.isActive()&&a.Oa)&&tgb(a,b),a.rb.start(910+b.rg.teaserDurationMs))}},tgb=function(a,b){a.ea.Gb?(b=new M4([0,
a.u.scrollTop],[0,b.SL.offsetTop],600,Afb),a.context.B.Ta(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ta(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.$Q(a.ea,!0),a.u.scrollTop=b.SL.offsetTop,g.$Q(a.ea,!1))},k5=function(a){return a.j&&a.j.rg?a.j.rg:a.cards[0]&&a.cards[0].rg?a.cards[0].rg:null},kgb=function(a,b){return g.Db(a.cards,function(c){return c.rg.id===b})},l5=function(a,b,c){b5.call(this,a,b);
this.annotation=c;this.isActive=!1},wgb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},m5=function(a,b,c){l5.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},xgb=function(a,b){var c=void 0===c?0:c;
var d=sfb(b).width;g.oo(b,d);c=new yfb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,zfb);g.H(a,c);a.context.B.Ta(c,"begin",function(){g.uo(b,!0)});
c.play()},Agb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Na:["iv-branding-context-name"],Aa:b.channel_name}),d=a.createElement({G:"div",Na:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.LU(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.I),a.j.Ja(d));var f=a.createElement({G:"div",Na:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Na:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.uo(h,!1);var l=a.createElement({G:"div",Na:["branding-context-container-outer"]});l.appendChild(h);g.Un(l,"right",b.image_width+"px");g.df(a.Bb(),l);a.B=new g.Kq(function(){ygb(a,h,l)},500);
g.H(a,a.B);a.context.j.Ta(a.Bb(),"mouseover",function(){zgb(a,h,l,f,b.image_height)});
a.context.j.Ta(a.Bb(),"mouseout",function(){a.B.start()})}},zgb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.to(b);a.j||(b.style.width=g.Zn(f.width,!0),c.style.width=g.Zn(f.width,!0));g.Un(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Un(d,"right","1px");a.C=!0;g.uo(b,!0);a.D=new g.Kq(function(){g.Sq(this.Bb(),"iv-branding-active")},0,a);
a.D.start()}},ygb=function(a,b,c){g.Uq(a.Bb(),"iv-branding-active");
a.J=new g.Kq(function(){g.uo(b,!1);a.j||(c.style.width=g.Zn(0,!0))},250);
a.J.start();a.C=!1},Bgb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},Cgb=function(a,b,c){l5.call(this,a,b,c);
var d=this;this.V=this.isCollapsed=this.ea=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Na:["iv-promo-contents"]});this.D=new g.Kq(function(){d.j.setAttribute("aria-hidden","true");g.uo(d.B,!1);g.uo(d.u,!0)},700,this);
g.H(this,this.D)},Egb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.Bb().setAttribute("aria-hidden","true");a.Bb().setAttribute("aria-label","Promotion");a.Bb().tabIndex=0;var e=a.annotation.kf(),f=b.image_url;if(f){var h=a.createElement({G:"div",Na:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({G:"span",S:"iv-promo-video-duration",Aa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",S:"iv-promo-playlist-length",Aa:b.playlist_length.toString()}),h.appendChild(f));e&&c5(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",S:"iv-promo-txt"}),g.ne(f,X4(e)),a.j=f):a.j=a.createElement({G:"div",S:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",X:[{G:"strong",Aa:b.text_line_1}]});
var m=a.createElement({G:"p",X:[{G:"span",S:"iv-promo-link",Aa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Na:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Na:["iv-button","iv-promo-button"],X:[{G:"span",S:"iv-button-content",Aa:f}]});var p=a.createElement({G:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&c5(a,a.Bb(),e,a.annotation.id,b.session_data,void 0,c)}g.Sq(a.j,"iv-click-target");
e&&c5(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",X:[{G:"span",Aa:b.text_line_1}]}),m=a.createElement({G:"p",X:[{G:"strong",Aa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Na:["yt-badge","iv-promo-badge-live"],Aa:"LIVE NOW"})),g.Sq(a.j,"iv-click-target"),e&&c5(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&a.K.appendChild(p);
c=a.createElement({G:"div",S:"iv-promo-actions"});a.u=a.createElement({G:"button",Na:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Ta(a.u,"click",function(q){Dgb(a,5E3,q)});
c.appendChild(a.u);g.uo(a.u,!1);a.context.j.Ta(a.Bb(),"mouseover",a.j5,a);a.context.j.Ta(a.Bb(),"mouseout",a.i5,a);a.context.j.Ta(a.Bb(),"touchend",function(q){Dgb(a,5E3,q)});
a.B=a.createElement({G:"button",Na:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Ta(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.e5:a.d5,a);c.appendChild(a.B);g.Tq(a.Bb(),d);h&&(g.df(a.Bb(),h),n&&h.appendChild(n));g.df(a.Bb(),a.K);g.df(a.Bb(),c)},Dgb=function(a,b,c){c.stopPropagation();
Fgb(a);Ggb(a,b);a.j.focus()},Hgb=function(a){a.isCollapsed||a.V||a.C||(g.Sq(a.Bb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},Fgb=function(a){a.D.stop();
a.isCollapsed&&(g.Vq(a.Bb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.uo(a.u,!1),g.uo(a.B,!0))},Ggb=function(a,b){a.C||(a.C=g.bg(function(){Igb(this);
Hgb(this)},b,a))},Igb=function(a){a.C&&(g.Pa.clearTimeout(a.C),a.C=null)},Jgb=function(a){this.I=a},mgb=function(a,b,c){b&&(c?n5(a,b.map(function(d){return g.zq(d,c)})):n5(a,b))},n5=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.wD(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},Kgb=function(a){g.WT.call(this,a);
var b=this;this.ea=this.K=!1;this.loadNumber=0;this.J={};this.logger=new Jgb(this.player);this.C=new g.PK(this);this.D=this.Yw=null;this.events=new g.PK(this);this.wh=this.V=this.j=null;this.oa=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ra("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.w0,this);this.subscribe("resize",this.qI,this);this.player.W().Ma.subscribe("vast_info_card_add",this.fY,this);g.H(this,this.events);this.qa=this.createElement({G:"div",S:"video-custom-annotations"});this.u=new g.X({G:"div",Na:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.XS(this.player,this.u.element,4);this.u.hide();this.B=new g.X({G:"div",Na:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",S:"video-annotations"});
a.appendChild(this.qa);this.B.element.appendChild(a);this.Ow()&&this.load();var c=this.createElement({G:"style"});(g.Ke("HEAD")[0]||document.body).appendChild(c);g.tb(this,function(){g.pf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Lgb=function(a){a=a.createElement({G:"div",
Na:["annotation","annotation-type-custom"]});g.uo(a,!1);return a},Mgb=function(a,b){b=!b.isCued()&&!g.yP(b,1024);
g.$Q(a.u,b);g.$Q(a.B,b)},Ngb=function(a,b,c){a.K=!0;
a.D=g.hA(b,c)},Ogb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Xa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ogb(a,e))}return c},Sgb=function(a){var b=a.player.getVideoData();
if(b.Va){var c=a.player.W().Ma.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.aA(h)&&h.responseXML?h.responseXML:null)&&Pgb(a,h)}};
g.MB()&&(d.onFinish=Qgb(a,d.onFinish));d.postParams={ic_only:"1"};Rgb(d,c);a.K=!0;g.hA(b.Va,d)}}},Rgb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.XB&&(a.postParams.ic_coll=b.XB);b.TL&&(a.postParams.ic_xml=b.TL);b.FJ&&(a.postParams.ic_track=b.FJ)},Tgb=function(a){var b=new g.X({G:"div"});
g.uo(b.element,!1);var c=new hgb(a.player,b.element,o5(a));g.H(c,b);b.Ja(a.u.element);c.SE();return c},Vgb=function(a,b){var c,d;
if(b=null==(c=b.Ad)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ea=!0,Ugb(a,b),b.headerText&&a.wh&&(c=g.VG(b.headerText),a.wh.setAttribute("title",c))},o5=function(a){if(!a.V){var b=new Bfb(a);
g.H(a,b);var c=new g.Zl(a);g.H(a,c);a.V=new Bgb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Pi)}return a.V},Pgb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.sH();if(e){var f=g.rH();f&&g.Nz(g.aCa)(void 0,e,f,[g.pH(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ogb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=W4(f.type,Wgb),p=W4(f.style,Xgb),q=Rfb(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=Xfb;if(null==v)var y=null;else if(g.Wa(v)){l=[];for(var A=g.u(v),E=A.next();!E.done;E=A.next()){var K=f(E.value);
K&&l.push(K)}y=l}else{var I=f(v);y=I?[I]:[]}e=m&&n?new Yfb(m,n,p,y,t):null}else e=null}catch(na){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=Lgb(f),S=null;switch(l.type){case "branding":if(f.player.W().Wd)break;f.u.element.appendChild(F);S=new m5(F,o5(f),l);break;case "promotion":g.XS(f.player,F,4),S=new Cgb(F,o5(f),l)}S&&S.SE();if(f=S)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Tgb(a),g.H(a,a.j));if("card"===e.type){c=a.j;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={hW:l.impression,click:l.click,close:l.close,IZ:l.teaser_impression,CJ:l.teaser_click},F=f.tracking_params||{},S=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:F.card?g.pH(F.card):null,zl:F.teaser?g.pH(F.teaser):null,xg:F.icon?g.pH(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,wY:f.image_url,title:f.title,metaInfo:f.meta_info,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:F.card?g.pH(F.card):null,zl:F.teaser?
g.pH(F.teaser):null,xg:F.icon?g.pH(F.icon):null,dF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "productListing":f.signin_url&&(S=Y4({target:"current",value:f.signin_url}));Y=[];for(var ia=f.offers||[],ta=0;ta<ia.length;ta++)Y.push(new dgb(g.De(ia[ta].merchant),g.De(ia[ta].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:F.card?g.pH(F.card):null,zl:F.teaser?g.pH(F.teaser):null,xg:F.icon?g.pH(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,VB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),wdb:S,vdb:f.signin_title?f.signin_title:void 0,udb:f.signin_message?f.signin_message:void 0,offers:Y,onClickCommand:null};g5(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:F.card?g.pH(F.card):
null,zl:F.teaser?g.pH(F.teaser):null,xg:F.icon?g.pH(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,VB:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};g5(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:F.card?g.pH(F.card):null,zl:F.teaser?g.pH(F.teaser):null,xg:F.icon?g.pH(F.icon):null,dF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Y4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},g5(c,e)}}else igb(a.j,e);c=!0}}c&&
(H4(a.player),a.qI())},Ugb=function(a,b){var c=!1;
a.j||(a.j=Tgb(a),g.H(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(jgb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.JO(f)||(c=a.j,d=b.headerText?g.VG(b.headerText):"",g.sf(c.Zb,d),c.V&&c.V.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.pH(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.pH(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.xg=b.icon.infoCardIconRenderer.trackingParams?g.pH(b.icon.infoCardIconRenderer.trackingParams):null,a.qI());H4(a.player)}},Ygb=function(a,b,c,d,e){if(!a.player.W().Wd){var f=[];
b.navigationEndpoint&&g.Q(b.navigationEndpoint,g.z3)&&g.Q(b.navigationEndpoint,g.z3).browseId&&f.push(new Ufb("openUrl","click",new Sfb("/channel/"+g.Q(b.navigationEndpoint,g.z3).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.Q(b.subscribeButton,
g.CO)){d.channel_id=g.Q(b.subscribeButton,g.CO).channelId;var l;b=g.Q(b.subscribeButton,g.CO);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.VG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.VG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.VG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.VG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.Q(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.A3))?void 0:m.url)||"";l={subscribeText:g.VG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.VG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Yfb(c,"branding","branding",f,d);l=Lgb(a);a.u.element.appendChild(l);f=new m5(l,o5(a),f);f.SE();g.H(f,f);a.J[c]=f}},Qgb=function(a,b){return function(){var c=g.Ia.apply(0,arguments);
a.isDisposed()||a.oa.push(g.Cq.Ki(function(){b.apply(null,g.qa(c))}))}},Zgb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.PS.prototype.yA=g.da(19,function(a,b){var c=g.lU(this.Fb());c&&c.yA(a,b)});
var J4={},K4=null;g.jb(M4,g.dr);g.k=M4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.wd())return!1;L4(this);this.startTime=a=g.eb();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.iI();this.Wl("play");-1==this.j&&this.Wl("resume");this.j=1;var b=g.ab(this);b in J4||(J4[b]=this);ufb();vfb(this,a);return!0};
g.k.stop=function(a){L4(this);this.j=0;a&&(this.progress=1);wfb(this,this.progress);this.Wl("stop");this.vr()};
g.k.pause=function(){this.wd()&&(L4(this),this.j=-1,this.Wl("pause"))};
g.k.xa=function(){0==this.j||this.stop(!1);this.Wl("destroy");M4.Uf.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.lK=function(){this.Wl("animate")};
g.k.Wl=function(a){this.dispatchEvent(new xfb(a,this))};
g.jb(xfb,g.yb);g.jb(N4,M4);N4.prototype.B=function(){};
N4.prototype.lK=function(){this.B();N4.Uf.lK.call(this)};
N4.prototype.vr=function(){this.B();N4.Uf.vr.call(this)};
N4.prototype.iI=function(){this.B();N4.Uf.iI.call(this)};
g.jb(yfb,N4);yfb.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.x(Bfb,g.G);g.k=Bfb.prototype;g.k.Ta=function(a,b,c,d){c=(0,g.bb)(c,d||this.u);a=g.fB(a,b,c);this.j.push(a);return a};
g.k.JH=function(a,b,c,d){c=(0,g.bb)(c,d||this.u);a=g.sna(a,b,c);this.j.push(a);return a};
g.k.Mc=function(a){g.gB(a);g.Hb(this.j,a)};
g.k.Tf=function(){g.gB(this.j);this.j.length=0};
g.k.xa=function(){this.Tf();g.G.prototype.xa.call(this)};g.x(Efb,g.WT);g.k=Efb.prototype;g.k.load=function(){g.WT.prototype.load.call(this);if(!Q4(this)){var a=g.Rza(this.player.getVideoData());a?(a=Dfb(a,Ffb(this)),R4(this,a,!1)):Gfb(this)}};
g.k.unload=function(){R4(this,null);this.B&&(this.B.abort(),this.B=null);g.WT.prototype.unload.call(this)};
g.k.Ih=function(a,b){return Q4(this)?"loadCustomEndscreenRenderer"===a?(a=Dfb(b,"new"),R4(this,a),!0):null:null};
g.k.getOptions=function(){return Q4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Kb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<$gb.length;f++){var h=Math.abs(b.width-$gb[f]);if(-1===e||d>=h)e=f,d=h}d=ahb[e];this.u&&g.Un(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.so(e.element,m,f);g.oo(e.element,n,p);g.Vq(e.element,bhb);256<m||256<f?g.Sq(e.element,"ytp-ce-large-round"):96<m||96<f?g.Sq(e.element,"ytp-ce-medium-round"):g.Sq(e.element,"ytp-ce-small-round");g.Vq(e.element,chb);m=h.left+h.width/2;h=h.top+l/2;g.Sq(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Vq(e.element,ahb);g.Sq(e.element,d);(e=g.Le(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Un(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V4(this,this.endscreen.impressionUrls),(a=g.sH())&&this.endscreen.visualElement&&g.nQ(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.Sq(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.Sq(b,"ytp-ce-shown");V4(this,c.impressionUrls);(b=g.sH())&&g.nQ(b,c.visualElement);this.player.W().J&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Uq(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Uq(b,"ytp-ce-shown");this.player.W().J&&this.player.Qa("endscreenelementhidden",a)}};
g.k.r9=function(a){var b=this;a.target===window&&(new g.Kq(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Vq(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var $gb=[346,426,470,506,570,640,853,1280,1920],ahb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),chb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],bhb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Tfb={ppa:"current",JOa:"new"};var Vfb={CLOSE:"close",kSa:"openUrl",SUBSCRIBE:"subscribe"},Wfb={Una:"click",CLOSE:"close",tAa:"hidden",aXa:"rollOut",bXa:"rollOver",AYa:"shown"};Yfb.prototype.kf=function(){var a=Zfb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Xgb={Via:"anchored",L_:"branding",CHANNEL:"channel",fpa:"cta",wAa:"highlightText",uEa:"label",PLAYLIST:"playlist",FUa:"popup",v0a:"speech",SUBSCRIBE:"subscribe",H3a:"title",VIDEO:"video",N9a:"website"},Wgb={L_:"branding",Qla:"card",ora:"drawer",vAa:"highlight",tKa:"marker",VVa:"promotion",TEXT:"text",pab:"widget"};g.x(b5,g.G);g.k=b5.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.NG(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.kb.set(a,e);this.context.I.hf([a])};
g.k.SE=function(){this.context.u.subscribe("resize",this.cG,this)};
g.k.Bb=function(){return this.element};
g.k.mK=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.pf(this.Bb())};
g.k.cG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=X4(a);if(f){var h=fgb(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.Dd||!1,n=g.Tz(f||"");m&&n&&(n.v||n.list)?e.context.I.xo(n.v,b,n.list,!1):g.sP(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);n5(this.context.logger,c,l,d);egb(f)||(c=g.sH(),d=b.itct,c&&d&&g.qQ(c,g.pH(d)))}};
g.k.xa=function(){this.eb.clear();this.kb.clear();g.G.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.x(hgb,b5);g.k=hgb.prototype;g.k.vt=function(){this.qa&&g5(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.to(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.cG=function(){var a=this.isAvailable();g.uo(this.Bb(),a);g.Wq(this.context.I.getRootNode(),g.xX.IV_DRAWER_ENABLED,a);H4(this.I)};
g.k.destroy=function(){this.I.yA(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.OD(this.oa);g.nB(this.Va);this.Ya&&this.Ya.dispose();this.D&&this.D.dispose();b5.prototype.destroy.call(this)};
g.k.T3=function(){if(this.B){n5(this.context.logger,k5(this).bj.close);var a=g.sH();a&&this.K&&g.qQ(a,this.K);f5(this)}};
g.k.n4=function(){g.Wq(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.c6=function(){var a=g.sH(),b=k5(this);b=b?b.xg:this.xg;a&&b&&g.oQ(a,[b])};
g.k.b6=function(){var a=g.sH(),b=k5(this);b=b?b.xg:this.xg;a&&b&&g.pQ(a,[b])};
g.k.v0=function(){var a=k5(this);n5(this.context.logger,a.bj.IZ);var b=g.sH();b&&a&&g.oQ(b,[a.zl,a.xg])};
g.k.d6=function(){var a=g.sH(),b=k5(this);a&&b&&g.pQ(a,[b.zl])};
g.k.u0=function(a){var b=k5(this),c=g.sH();this.j?a?(a=this.context.logger,n5(a,b.bj.CJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.zl&&g.qQ(c,b.zl)):(a=this.context.logger,n5(a,b.bj.CJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.xg&&g.qQ(c,b.xg)):(a=this.context.logger,n5(a,b.bj.CJ),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.xg&&g.qQ(c,this.xg))};g.x(l5,b5);l5.prototype.SE=function(){b5.prototype.SE.call(this);wgb(this)};
l5.prototype.show=function(){b5.prototype.show.call(this);var a=g.sH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.oQ(a,[g.pH(b.itct)])};
l5.prototype.hide=function(){b5.prototype.hide.call(this);var a=g.sH(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.pQ(a,[g.pH(b.itct)])};g.x(m5,l5);
m5.prototype.show=function(){if(!this.isActive){l5.prototype.show.call(this);if(!this.K){g.Sq(this.Bb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Na:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.uo(this.u,!1);var b=this.createElement({G:"button",Na:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.Bb().appendChild(b);var c=this.annotation.kf();c&&c5(this,b,
c,this.annotation.id,a.session_data);Agb(this,a);this.K=!0}g.uo(this.Bb(),!0);this.isActive=!0;if(this.u){try{xgb(this,this.u)}catch(d){}g.Sq(this.context.I.getRootNode(),"ytp-branding-shown")}}};
m5.prototype.hide=function(){this.isActive&&(l5.prototype.hide.call(this),g.uo(this.Bb(),!1),this.isActive=!1,g.Uq(this.context.I.getRootNode(),"ytp-branding-shown"))};
m5.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);l5.prototype.destroy.call(this)};g.x(Cgb,l5);g.k=Cgb.prototype;g.k.show=function(){this.isActive||(l5.prototype.show.call(this),this.ea||(Egb(this),this.ea=!0),g.uo(this.Bb(),!0),g.bg(function(){g.Uq(this.Bb(),"iv-promo-inactive")},100,this),this.Bb().removeAttribute("aria-hidden"),this.isActive=!0,Igb(this),Fgb(this),Ggb(this,this.J))};
g.k.hide=function(){this.isActive&&(g.Sq(this.Bb(),"iv-promo-inactive"),this.isActive=!1,this.Bb().setAttribute("aria-hidden","true"))};
g.k.mK=function(a,b,c,d,e,f){return this.isCollapsed?!1:l5.prototype.mK.call(this,a,b,c,d,e,f)};
g.k.j5=function(a){this.V=!0;Dgb(this,500,a)};
g.k.i5=function(){this.V=!1;Hgb(this)};
g.k.d5=function(a){a.stopPropagation();this.hide()};
g.k.e5=function(a){a.stopPropagation();Igb(this);this.isCollapsed=!0;g.Sq(this.Bb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();l5.prototype.destroy.call(this)};g.x(Kgb,g.WT);g.k=Kgb.prototype;g.k.Ih=function(a,b){if(!Zgb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.H$a(b))&&Pgb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(lgb(this.j,b),H4(this.player)),!0}return null};
g.k.getOptions=function(){return Zgb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Ow=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Dd&&a.oa||g.JS(this.player.app)?!1:1===c&&!b.sT||a.Ma.get(b.videoId)||g.KO(b)||g.Sza(b)?!0:!1};
g.k.qI=function(){if(this.B){var a=this.player.qb().getVideoContentRect(!0);g.so(this.B.element,a.width,a.height);g.oo(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Vk();a=this.j;b=b.width;g.Wq(a.C,"iv-drawer-small",426>=b);g.Wq(a.C,"iv-drawer-big",1280<=b)}};
g.k.w0=function(a){Mgb(this,a.state);g.yP(a.state,2)&&(this.Mk()&&this.So()&&2!==this.player.getPresentingPlayerType()&&this.zA(!1),this.yA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.aA(h)&&h.responseXML?h.responseXML:null)&&(Pgb(b,h),g.Sq(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.WT.prototype.load.call(this);Mgb(this,this.player.Nb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.MB()&&(a=Qgb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Ma.get(d);f&&Rgb(e,f);f=f&&(f.TL||f.XB);if(!c.mx||f)c.Va?Ngb(this,c.Va,e):(this.Yw=function(){if(!b.K)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.JO(h))&&!b.ea&&Vgb(b,h)},this.player.addEventListener("videodatachange",this.Yw));
g.XS(this.player,this.B.element,4);this.qI();(f=g.KO(c))&&Ugb(this,f);(f=g.Sza(c))&&f.featuredChannel&&Ygb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.wh=g.Ne("ytp-cards-button",this.player.getRootNode());g.JO(c)&&Vgb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Va&&Ngb(this,b.Va,a)};
g.k.unload=function(){this.player.Se("annotations_module");for(var a=g.u(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.V=null;this.j&&(this.j.destroy(),this.j=null,H4(this.player));this.K=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.J={};this.u.hide();g.WT.prototype.unload.call(this);this.B.detach();this.Yw&&(this.player.removeEventListener("videodatachange",this.Yw),this.Yw=null)};
g.k.fY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Sgb(this):this.load())};
g.k.Mk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.So=function(){return!!this.j&&this.j.B};
g.k.zA=function(a,b,c){b=void 0===b?!1:b;this.Mk();this.j&&(a?c?e5(this.j,c,b):e5(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):f5(this.j))};
g.k.yA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.W().Ma.unsubscribe("vast_info_card_add",this.fY,this);g.Uq(this.player.getRootNode(),g.xX.IV_DRAWER_OPEN);for(var a=this.oa,b=g.Cq,c=0,d=a.length;c<d;c++)b.Tj(a[c]);this.oa.length=0;g.WT.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.X(a);g.H(this,a);return a.element};g.VT("annotations_module",Kgb);g.VT("creatorendscreen",Efb);})(_yt_player);
